/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tiobe.julia;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RulesTests {
    private static final class TestCase {
        public int number;
        public String path;
        public TestCase(final int number, final String path) {
            this.number = number;
            this.path = path;
        }
    }

    private static Optional<TestCase> getTestFile(final int number) {
        return Optional.ofNullable(RulesTests.class.getResource(String.format("/com/tiobe/julia/Rule%s.jl", number)))
                .map(URL::getFile)
                .map(File::new)
                .map(File::getAbsolutePath)
                .map(x -> new TestCase(number, x));
    }

    public static List<Arguments> getTestFiles() {
        return IntStream.iterate(1, i -> i + 1)
                .mapToObj(RulesTests::getTestFile)
                .takeWhile(Optional::isPresent)
                .map(Optional::get)
                .map(x -> Arguments.of(Integer.toString(x.number), x.path))
                .collect(Collectors.toUnmodifiableList());
    }

    public static List<Integer> getExpectedViolationLineNumbers(final List<String> lines) {
        final List<Integer> lineNumbers = new ArrayList<>();
        for (int i = 0; i < lines.size(); i++) {
            final String line = lines.get(i);
            final int lineNumber = i + 1;
            Matcher matcher = Pattern.compile("# Violation([^+]|$)").matcher(line);
            while (matcher.find()) {
                lineNumbers.add(lineNumber);
            }
            // Allow e.g. # Violation+3 to indicate a violation 3 lines ahead. This is needed because Gherkin has no EOL comments
            matcher = Pattern.compile("# Violation\\+(\\d)").matcher(line);
            while (matcher.find()) {
                lineNumbers.add(lineNumber + Integer.parseInt(matcher.group(1)));
            }
        }
        return lineNumbers;
    }

    @ParameterizedTest(name = "testRule{0}")
    @MethodSource("getTestFiles")
    public void testRule(final String rule, final Path path) throws IOException {
        final String contents = Files.readString(path);
        final List<String> lines = contents.lines().collect(Collectors.toUnmodifiableList());
        final List<Integer> expected = getExpectedViolationLineNumbers(lines);
        final List<Violation> violations = App.getViolations(path.toString(), List.of("Rule" + rule));
        violations.forEach(x -> x.printToStdout(path.toString()));
        final List<Integer> actual = violations.stream()
                .map(Violation::getLineNumber)
                .sorted()
                .collect(Collectors.toUnmodifiableList());

        assertEquals(expected, actual);
    }
}
