name: Build

on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:      
        java-version: 11
    - name: Build
      working-directory: ./checker
      run: ./gradlew clean build jacocoTestReport
