name: TICS Analyzer

on:
  schedule:
    - cron: "00 00 * * *"

jobs:
  TICSQServer:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - run: ./gradlew jacocoTestReport
      - name: Install and run TICSQSERVER
        env:
          TICSAUTHTOKEN: ${{ secrets.EBOIT_ANALYZER_TOKEN }}
        run: |
          . <(curl --silent --show-error "https://eboit.tiobe.com/tiobeweb/TICS/api/public/v1/fapi/installtics/Script?cfg=main&platform=linux&url=https://eboit.tiobe.com/tiobeweb/TICS/")
          TICSQServer -project 'DutchRomeo' -branchdir .
